AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Lambda function using CodePipeline artifact

Resources:
  ImageRekognitionLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ImageRekognitionLambda
      Handler: lf1.lambda_handler
      Runtime: python3.11
      Role: arn:aws:iam::311141533881:role/LambdaExecutionRole
      Code:
        S3Bucket: lambda-artifacts-user1
        S3Key: lambda-deploy.zip
      Timeout: 10
      MemorySize: 128
